### ISSUE TITLE
请问项目如何在本地跑起来

### ISSUE THREAD

**Issue by ghjkg546** [deep-project/moss#10]
我进了main目录，运行go run cmd/web/main.go，只能访问前台，admin访问不了

**Comment by ArcaneLorder** [comment]
You just need to create an arbitrary file on the admin direcroty.

**Comment by deep-project** [comment]
你如果要源码编译，需要先编译前端的admin后台，然后再编译golang。如果只是使用，可以直接下载已编译好的版本。
