### ISSUE TITLE
Warning Others: What does owner want to track?

### ISSUE THREAD

**Issue by vuhoanglam** [deep-project/moss#11]
![image](https://github.com/deep-project/moss/assets/59502855/86b6543f-8baa-4e07-9256-e18e8094f3c8)
![image](https://github.com/deep-project/moss/assets/59502855/d233fbb4-b9ee-47f3-9887-70901d807731)
![image](https://github.com/deep-project/moss/assets/59502855/b98641b4-ac63-4df8-b7ed-734e85ea70a7)

**Comment by deep-project** [comment]
I just want to track the usage numbers. It won't cause any harm. If you’re not comfortable with that, feel free not to use it.

**Comment by deep-project** [comment]
Thank you for your kind words! I'm thrilled that you find my CMS useful and appreciate your feedback.
